name: Recent Group Projects
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-recent-group-projects:
    name: Update this repos README with best projects of the best
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          comment_tag_name: "RECENT-GROUP-PROJECTS-LIST"
          feed_list: "https://grobert.eu/feed/group-projects/"